### ISSUE TITLE
CsvProvider.Load loads relative to executable not current working directory

### ISSUE THREAD

**Issue by daz10000** [fsharp/FSharp.Data#1105]
This may be by design? but I just ran into an odd case which broke the user experience for a bunch of people.   I have a program using CsvProvider that uses the Load method and a relative path is used to load a file.   The attempted load path is relative to the location of the executable not the current working directory (win10,  gitbash shell).   For example

```
current folder
     subfolderA
       subfolderB
          mytool.exe

    subfolderC
       datafile.txt

```
Invoking a load from the current folder `subfolderA/subfolderB/mytool.exe  subfolderC/datafile.txt`    where the path is passed into CsvProvider.Load  would result in an attempt to load `subfolderA/subfolderB/subFolderC/datafile.txt` instead of `subFolderC/datafile.txt`    

I consider that to be a bug (other methods like File.ReadAllText(relativePath) will produce the expected result),  but maybe there's a reason for those sematics  ?  (you won't notice if you run in same folder as the binary).    I did a workaround using the File.ReadAllText method and the .Parse method of CsvProvider but it's a bit annoying

Darren
FSharp.Data 2.4.2

**Comment by daz10000** [comment]
NB:  same problem with XmlProvider.   Annoying to not be able to run ```/path/to/binary.exe *.xml```     to parse local files.

**Comment by ovatsus** [comment]
It's by design, to make it easier to work with fsi

**Comment by daz10000** [comment]
Could we discuss this then a little rather than just closing it.   It seems like you are catering to a strange quirk of fsi and breaking all other production use cases.  The end result you want (which is what I want) is to load relative to current working directory for fsi and a program.  Fsi seems to interpret   TP.Load("foo") as loading from current directory,  but a compiled binary will load relative to that binaries' location.   See attached example but same code for a simple script and same code as a compiled program.   

**Every other API across every language I've ever used loads relative to current working directory, so this behavior is going to trip up a lot of people.**

## script will load from current folder
```
#r @"c:/src/lib/FSharp.Data.dll"

open FSharp.Data
type Test = CsvProvider<"""a,b,c
1,2,3
2,2,2
3,3,3
""">


let x = Test.Load("test.csv")
for row in x.Rows do
    printf "%d" row.A
```

## same thing as a program will break in counterintuitive fashion
```
open System
open FSharp.Data

type Test = CsvProvider<"""a,b,c
1,2,3
2,2,2
3,3,3
""">

[<EntryPoint>]
let main argv =
    let x = Test.Load("test.csv")
    for row in x.Rows do
        printfn "%d" row.A
    0

```
```
Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'C:\src\gsl_web\src\Server\Common\Parts\test\bin\Debug\netcoreapp2.0\test.csv'.
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at FSharp.Data.Runtime.IO.asyncRead@221-5.Invoke(Unit unitVar) in C:\Git\FSharp.Data\src\CommonRuntime\IO.fs:line 222
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Program.main(String[] argv) in C:\src\gsl_web\src\Server\Common\Parts\test\Program.fs:line 12
```

**Comment by ovatsus** [comment]
Have a look at the current rules here -  https://github.com/fsharp/FSharp.Data/blob/master/src/CommonRuntime/IO.fs#L28 - 

The problem is that changing this to the current directory would break another set of cases, and would be a very nasty breaking change
