### ISSUE TITLE
CsvProvider Documentation - Google finance historical 

### ISSUE THREAD

**Issue by demonno** [fsharp/FSharp.Data#1138]
If you try to follow the [example](http://fsharp.github.io/FSharp.Data/library/CsvProvider.html) in the CsvProvider documentation, it is not working currently. 

```fsharp 
// Download the stock prices
let msft = Stocks.Load("http://www.google.com/finance/historical?q=MSFT&output=csv")

```

Fails here because google restricted access to historical finance data 

https://www.google.com/finance/historical?q=MSFT&output=csv

![image](https://user-images.githubusercontent.com/1255065/37863163-5dda47aa-2f62-11e8-8bc9-30388e074c05.png)

If there is an alternative API to get same data, this could be fixed easily.

**Comment by lashleykeith** [comment]
Have you found a way to work around this?  I am trying to use google finance data as well.

**Comment by vadimk2016** [comment]
Same problem, not work:
```
~: python -c "from pyalgotrade.tools import googlefinance; googlefinance.download_daily_bars('orcl', 2000, 'orcl-2000.csv')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pyalgotrade/tools/googlefinance.py", line 65, in download_daily_bars
    datetime.date(year, 12, 31))
  File "pyalgotrade/tools/googlefinance.py", line 39, in download_csv
    f = urllib2.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```
