### ISSUE TITLE
executeFSIWithArgs "docs/tools" "generate.fsx" is failing

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FSharp.Data#1142]
`build release` fails with this error:

    Running build failed.
    Error:
    System.Exception: Start of process fsi.exe failed. The system cannot find the file specified
       at Fake.ProcessHelper.ExecProcessWithLambdas@103-16.Invoke(String message) in D:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 103
       at Fake.ProcessHelper.ExecProcessWithLambdas(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut, Boolean silent, FSharpFunc`2 errorF, FSharpFunc`2 messageF) in D:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 103
       at Fake.FSIHelper.executeFSIWithArgs(String workingDirectory, String script, FSharpList`1 extraFsiArgs, IEnumerable`1 env) in D:\code\fake\src\app\FakeLib\FSIHelper.fs:line 186
       at FSI_0005.Build.clo@195-33.Invoke(Unit unitVar0)
       at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626

But manually running the entire build.fsx code inside VS or VSCode works fine

**Comment by ovatsus** [comment]
Or maybe it was because of the upgrade to F# SDK 10.1

**Comment by matthid** [comment]
Yes I assume they changed location of `fsi.exe` and fake doesn't find it anymore.

**Comment by ovatsus** [comment]
FAKE probably needs the equivalent of this: https://github.com/ionide/ionide-vscode-fsharp/pull/732

**Comment by matthid** [comment]
Yes indeed - a PR on the fake4_hotfix branch would be welcome ;)

**Comment by ovatsus** [comment]
Ah, I sent one to master, let me rebase that

**Comment by matthid** [comment]
thanks
