### ISSUE TITLE
JsonProvider infers Decimal when numbers may include exponential notation

### ISSUE THREAD

**Issue by WallaceKelly** [fsharp/FSharp.Data#1230]
The following code fails at runtime:

    type ExponentialDataTypes =
        FSharp.Data.JsonProvider< Sample = "{ \"mydata\": [ 1, 2.34567E5, 3.14 ] }" >

    [<EntryPoint>]
    let main argv =
        let r = ExponentialDataTypes.Parse("{ \"mydata\": [2, 3.45678E5, 9.01 ] }")
        printfn "An array of %s" (r.Mydata.[0].GetType().Name)
        printfn "%A" r.Mydata
        0 // return an integer exit code

It fails with this exception:

    Unhandled Exception: System.Exception: Expecting a Decimal at '/mydata[1]', got 345678
       at <StartupCode$FSharp-Data>.$JsonRuntime.GetNonOptionalValue@143-5.Invoke(String message)
       at Program.main@11.Invoke(IJsonDocument t)
       at Microsoft.FSharp.Collections.ArrayModule.MapIndexed[T,TResult](FSharpFunc`2 mapping, T[] array)
       at Program.main(String[] argv)

I have not dug into the code yet, but I would expect it has something to do with the fact that Decimal.Parse(...) cannot parse exponential notation by default, as described [here](https://stackoverflow.com/questions/3879463/parse-a-number-from-exponential-notation).

**Comment by alex75it** [comment]
Still no solution for this?
I  have a JSON like this: [ 2.8e-7, 1765236.7777692 ]  
I can parse it but it fails to read the exponencial notation:
let values = JsonValue.Parse(jsonString).AsArray()
let v1 = valeus.[0].AsDecimals()

**Comment by romanprocopie** [comment]
Another symptom if the sample is a list and the element is missing on some items.
It is correctly inferred as a decimal option, but when parsing a real json, will always return None for that field.

The workaround of using only exponential form in the sample works ok too. Many thanks
