### ISSUE TITLE
Worldbank requests result in 404 - Resource not found (v1 API was discontinued June 19, 2020)

### ISSUE THREAD

**Issue by zanedp** [fsharp/FSharp.Data#1324]
```
#r @"<...>\packages\FSharp.Data.3.3.3\lib\net45\FSharp.Data.dll"

open FSharp.Data

let data = WorldBankData.GetDataContext()
data.Countries
```

```
val it : WorldBankData.ServiceTypes.Countries =
  Error: Failed to request 'http://api.worldbank.org/country?per_page=1000&format=json&page=1'. Error: System.Net.WebException: The remote server returned an error: (404) Not Found.
Response from http://api.worldbank.org/country?per_page=1000&format=json&page=1:
{ "statusCode": 404, "message": "Resource not found" } ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at FSharp.Data.HttpHelpers.getResponseAsync@1319-4.Invoke(Exception _arg2) in C:\GitHub\dsyme\FSharp.Data\src\Net\Http.fs:line 1325
   at <StartupCode$FSharp-Core>.$Async.TryWith@1082-1.Invoke(Exception exn) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1082
   at Microsoft.FSharp.Control.AsyncPrimitives.CallFilterThenInvoke[T](AsyncActivation`1 ctxt, FSharpFunc`2 catchFilter, ExceptionDispatchInfo edi) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 435
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
   --- End of inner exception stack trace ---
   at FSharp.Data.HttpHelpers.augmentWebExceptionsWithDetails@1227-3.Invoke(Unit unitVar) in C:\GitHub\dsyme\FSharp.Data\src\Net\Http.fs:line 1238
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.AsyncPrimitives.unitAsync@589.Invoke(AsyncActivation`1 ctxt) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 589
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
```

Note that there is a v2 API that does respond with data.
```
type Countries = XmlProvider<"http://api.worldbank.org/v2/country">
let data = Countries.GetSample()
```
```
type Countries = XmlProvider<...>
val data : XmlProvider<...>.Countries =
  <wb:countries page="1" pages="7" per_page="50" total="304" xmlns:wb="http://www.worldbank.org">
  <wb:country id="ABW">
    <wb:iso2Code>AW</wb:iso2Code>
    <wb:name>Aruba</wb:name>
    <wb:region id="LCN" iso2code="ZJ">Latin America &amp; Caribbean </wb:region>
    <wb:adminregion id="" iso2code="" />
    <wb:incomeLevel id="HIC" iso2code="XD">High income</wb:incomeLevel>
    <wb:lendingType id="LNX" iso2code="XX">Not classified</wb:lendingType>
    <wb:capitalCity>Oranjestad</wb:capitalCity>
...
```

[It looks like the v1 API was retired in November 2018, and was totally discontinued on June 19, 2020.](https://datahelpdesk.worldbank.org/knowledgebase/articles/889392-about-the-indicators-api-documentation)

**Comment by stmax82** [comment]
https://fslab.org/getting-started/

... first tutorial fails due to api.worldbank.org returning 404...

**Comment by jackfoxy** [comment]
Is it as simple as changing 

`let defaultServiceUrl = "http://api.worldbank.org"`

to

`let defaultServiceUrl = "https://api.worldbank.org/v2/"`  (let's use https while we are at it) ?

I noticed in debugging this query generated by the TP returns 404 

`http://api.worldbank.org/indicator?per_page=1000&format=json&page=4`

and you can paste this query into a browser and it works

`https://api.worldbank.org/v2/indicator?per_page=1000&format=json&page=4`

**Comment by baronfel** [comment]
@jackfoxy this is solved in https://github.com/fsharp/FSharp.Data/pull/1320, we're just waiting for a maintainer to merge/approve.

**Comment by dsyme** [comment]
Merged
