### ISSUE TITLE
Encoding error on response?

### ISSUE THREAD

**Issue by MicaelMor** [fsharp/FSharp.Data#1342]
Hi,

I am getting the following error:

> System.ArgumentException: Specified value has invalid Control characters. (Parameter 'value')
   at System.Net.HttpValidationHelpers.CheckBadHeaderValueChars(String value)
   at System.Net.WebHeaderCollection.Set(String name, String value)
   at System.Collections.Specialized.NameValueCollection.set_Item(String name, String value)
   at System.Net.HttpWebResponse.get_Headers()
   at <StartupCode$FSharp-Data>.$Http.headers@1597-1.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 371
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 403
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at <StartupCode$FSharp-Data>.$Http.InnerRequest@1596-5.Invoke(WebResponse _arg2)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 416
   at <StartupCode$FSharp-Core>.$Async.AwaitAndBindChildResult@1511-4.Invoke(AsyncActivation`1 ctxt) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1511
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 350
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 882
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 890
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1154
   at Program.main(String[] argv) in C:\Users\Micael\RiderProjects\BancosDev\BancosDev\Program.fs:line 37

I believe this is an issue with FSharp.Data, possibly an encoding related issue, I have replicated the request using HttpClient, and it succeeds to parse the response, while it fails using FSharp.Data.

This is the code for HttpClient (the code that succeeds):

```fsharp
    let client = new HttpClient()
    client.DefaultRequestHeaders.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.66")
    client.DefaultRequestHeaders.Add("Accept-Encoding", "gzip, deflate")
    let response = client.GetStringAsync("https://www.empresas.santander.pt/canalempresas/finance/login.jsp") |> Async.AwaitTask |> Async.RunSynchronously
```

This is the code with FSharp.Data (The code that fails):

```fsharp
    let loginPage =
        Http.AsyncRequestString("https://www.empresas.santander.pt/canalempresas/finance/login.jsp",
                           headers = [("User-Agent","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.66")])
        |> Async.RunSynchronously
```

This is the result in fiddler for the HttpClient https://i.imgur.com/DpofMKX.png and this is the one for FSharp.Data https://i.imgur.com/gjDPnK5.png as can be seen both the Request and the response is virtually identical.

I have used FSharp.Data in the past in other websites with no issue, but this is the first website that sets the content type as charset=ISO-8859-1, and from what I was able to google it seems that the issue might be related to that, I have tried setting responseEncodingOverride = "ISO-8859-1", but that made no difference.

Any suggestion on how this might be solved would be appreciated.

Thank you.

**Comment by MicaelMor** [comment]
Loaded FSharp.Data to the project to be able to debug the issue better, and this happens when trying to access the resp.Headers.AllKeys, more precisely this happens just by accessing resp.Headers which is of type WebHeaderCollection, so I thought there might be something invalid with the values in Headers, but these are the values:

> Cache-Control: no-store, must-revalidate, no-cache
Date: Thu, 07 Jan 2021 09:02:57 GMT
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Content-Security-Policy: frame-ancestors 'self'
X-XSS-Protection: 1; mode=block
X-OneAgent-JS-Injection: true
Connection: Keep-Alive


And that does not seem to be the case to me, so after further debugging found out that it was the HttpValidationHelpers triggering the error, and it is down to the website server returning a Set-Cookie with an invalid character, this line to be specific:

> Set-Cookie: ___utmvaLwBuyPawZ=CpooKcn; path=/; Max-Age=900; Secure; SameSite=None

Since this is not an FSharp.Data problem I will be closing down this specific issue.
