### ISSUE TITLE
Documentation tests fail when run with NUnit (including on CI)

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FSharp.Data#587]
Executing the tests in FSI works fine. This is because of the call to `fsiSession.EvalExpression` in `FsiEvaluator`:

```
***** FSharp.Data.DesignTime.Tests.DocumentationTests.Documentation generated correctly ("library/CsvFile.fsx")
Processing 'library/CsvFile.fsx'
Unhandled Exception:
System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1
:24469

Server stack trace:
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Runtime.Remoting.Channels.RemoteConnection.CreateNewSocket(EndPoint ipEndPoint)
   at System.Runtime.Remoting.Channels.RemoteConnection.CreateNewSocket()
   at System.Runtime.Remoting.Channels.SocketCache.GetSocket(String machinePortAndSid, Boolean openNew)
   at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.SendRequestWithRetry(IMessage msg, ITransportHeaders r
equestHeaders, Stream requestStream)
   at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders request
Headers, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.IDisposable.Dispose()
   at NUnit.Core.ProxyTestRunner.Dispose()
   at NUnit.Util.ProcessRunner.Dispose()
   at NUnit.ConsoleRunner.ConsoleUi.Execute(ConsoleOptions options)
   at NUnit.ConsoleRunner.Runner.Main(String[] args)
```

@tpetricek, @dsyme any idea on how to fix this?

**Comment by matthid** [comment]
If this is still up2date you may be able to figure out the root cause with https://github.com/fsharp/FSharp.Compiler.Service/issues/317 and https://github.com/matthid/FSharp.Compiler.Service/commit/f8b1e1781906bbabb5c6a2eae61f1cb1c69962fb where I had the exact same issue. Note that the "real" error message might be lost in a buffer somewhere.

**Comment by ovatsus** [comment]
Tried reenabling this again with latest FF/FCS, there's no longer any error, but it just hangs on CsvProvider.fsx
