### ISSUE TITLE
CSVProvider failing on rich UTF8 files?

### ISSUE THREAD

**Issue by Rickasaurus** [fsharp/FSharp.Data#621]
I'm seeing some rather odd behavior, and it doesn't seem to matter which flags I use.  I tried it like this:

```fsharp
type extNamesType = CsvProvider<extNamesFile, HasHeaders = false, Separators = "\t_">
```

and I get error:

System.Exception: Couldn't parse row 429511 according to schema: Expected 5 columns, got 6
   at <StartupCode$FSharp-Data>.$CsvRuntime.data@189-1.Invoke(String message) in C:\Git\FSharp.Data SourceLink\src\Csv\CsvRuntime.fs:line 189
   at Microsoft.FSharp.Core.PrintfImpl.go@523-3[b,c,d](String fmt, Int32 len, FSharpFunc`2 outputChar, FSharpFunc`2 outa, b os, FSharpFunc`2 finalize, FSharpList`1 args, Int32 i)
   at Microsoft.FSharp.Core.PrintfImpl.run@521[b,c,d](FSharpFunc`2 initialize, String fmt, Int32 len, FSharpList`1 args)
   at <StartupCode$FSharp-Core>.$Reflect.Invoke@720-4.Invoke(T1 inp)
   at <StartupCode$FSharp-Data>.$CsvRuntime.data@184.GenerateNext(IEnumerable`1& next) in C:\Git\FSharp.Data SourceLink\src\Csv\CsvRuntime.fs:line 188
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Collections.SeqModule.oneStepTo@1219[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i)
   at Microsoft.FSharp.Collections.SeqModule.f@4244-2[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i, Unit unitVar0)
   at Microsoft.FSharp.Collections.SeqModule.result@1235.Invoke(Int32 i)
   at Microsoft.FSharp.Collections.IEnumerator.unfold@190.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at FSI_0037.extNames@24-9.GenerateNext(IEnumerable`1& next) in J:\Basis\DJ vs DJ Extended Unicode\DJETL\DJETL\LoadAndGraph.fsx:line 24
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at <StartupCode$FSI_0037>.$FSI_0037.main@() in J:\Basis\DJ vs DJ Extended Unicode\DJETL\DJETL\LoadAndGraph.fsx:line 22
Stopped due to error

Oddly, I manually investigated that line and those around it, here was no extra tab or underline.  So I tried:

```fsharp
type extNamesType = CsvProvider<extNamesFile, HasHeaders = false, Separators = "\t_", IgnoreErrors = true>
```

and it only took 648,902 lines of the file.  The actual number of rows in the file is 2,317,134.  I have another smaller file (975,488 lines) I wrote using the same procedure and didn't get any errors.  Any idea what might be going wrong?

**Comment by ovatsus** [comment]
ping again :)

**Comment by ovatsus** [comment]
Closing until we get a repro
