### ISSUE TITLE
SQL type provider bug

### ISSUE THREAD

**Issue by jdh30** [fsharp/FSharp.Data#778]
When using FSharp.Data 2.1.0, I get this every now and again whilst using the SQL type provider:

System.InvalidOperationException: Invalid attempt to call FieldCount when reader is closed.
   at System.Data.SqlClient.SqlDataReader.get_FieldCount()
   at System.Data.Linq.SqlClient.ObjectReaderCompiler.ObjectReaderSession`1.GetActiveNames()
   at System.Data.Linq.SqlClient.ObjectReaderCompiler.ObjectReaderBase`1.Buffer()
   at System.Data.Linq.SqlClient.ObjectReaderCompiler.ObjectReaderSession`1.Buffer()
   at System.Data.Linq.SqlClient.SqlConnectionManager.BootUser(IConnectionUser user)
   at System.Data.Linq.SqlClient.SqlConnectionManager.UseConnection(IConnectionUser user)
   at System.Data.Linq.SqlClient.SqlProvider.Execute(Expression query, QueryInfo queryInfo, IObjectReaderFactory factory, Object[] parentArgs, Object[] userArgs, ICompiledSubQuery[] subQueries, Object lastResult)
   at System.Data.Linq.SqlClient.SqlProvider.ExecuteAll(Expression query, QueryInfo[] queryInfos, IObjectReaderFactory factory, Object[] userArguments, ICompiledSubQuery[] subQueries)
   at System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   at System.Data.Linq.DataQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at Microsoft.FSharp.Collections.SeqModule.Head[T](IEnumerable`1 source)
   at <StartupCode$FSI_0201>.$FSI_0201.main@()
Stopped due to error

Maybe when something has timed out.

**Comment by ovatsus** [comment]
SQL type provider is not part of FSharp.Data

**Comment by jdh30** [comment]
Oh, sorry. What package is responsible for Microsoft.FSharp.Data.TypeProviders.SqlDataConnection then?

**Comment by ovatsus** [comment]
That's distributed with VisualStudio, it's part of the fsharp core

**Comment by ovatsus** [comment]
https://github.com/Microsoft/visualfsharp
