### ISSUE TITLE
Http, bug, handling of '#' in url

### ISSUE THREAD

**Issue by xenocons** [fsharp/FSharp.Data#790]
```
> FSharp.Data.Http.Request ("http://www.google.com/#1");;
> System.ArgumentOutOfRangeException: StartIndex cannot be less than zero.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at FSharp.Data.Runtime.UriUtils.uriInfo(Uri uri, String source) in C:\Users\david\Desktop\FSharp.Data\src\Net\UriUtils.fs:line 36
   at FSharp.Data.Runtime.UriUtils.purifierDotNet@63-1.Invoke(Uri uri) in C:\Users\david\Desktop\FSharp.Data\src\Net\UriUtils.fs:line 78
   at FSharp.Data.Http.InnerRequest[a,b](String url, FSharpFunc`2 toHttpResponse, FSharpOption`1 query, FSharpOption`1 headers, FSharpOption`1 httpMethod, FSharpOption`1 body, FSharpOption`1 cookies, FSharpOption`1 cookieContainer, FSharpOption`1 silentHttpErrors, FSharpOption`1 responseEncodingOverride, FSharpOption`1 customizeHttpRequest) in C:\Users\david\Desktop\FSharp.Data\src\Net\Http.fs:line 704
   at FSharp.Data.Http.Request(String url, FSharpOption`1 query, FSharpOption`1 headers, FSharpOption`1 httpMethod, FSharpOption`1 body, FSharpOption`1 cookies, FSharpOption`1 cookieContainer, FSharpOption`1 silentHttpErrors, FSharpOption`1 responseEncodingOverride, FSharpOption`1 customizeHttpRequest) in C:\Users\david\Desktop\FSharp.Data\src\Net\Http.fs:line 864
   at <StartupCode$FSI_0089>.$FSI_0089.main@()
Stopped due to error
```

The culprit appears to be that the uriInfo function assumes that if there is a '#' character, there must also be a '?' character, I am not knowledgeable enough about Http to fix this in a pull request.

Edit: fixed the input URL to make it a valid URL

**Comment by ovatsus** [comment]
Can you just request "http://www.google.com/" as a workaround? The `#1` won't change in any way the html output of any uri.
I've marked this as up for grabs

**Comment by xenocons** [comment]
I can trim the #.. off I think as a workaround.

**Comment by ovatsus** [comment]
This is this bug https://github.com/Purify-net/PUrify/issues/33
