### ISSUE TITLE
CsvProvider and missing columns

### ISSUE THREAD

**Issue by xkrt** [fsharp/FSharp.Data#869]
Hi, I have a problem with `CsvProvider` and my data, which may sometimes miss some columns (and I know what columns may be missed).

Csv provider:
```fsharp
[<Literal>]
let inferSample = """
"one","two","three"
42,"hello",3.14"""

type Csv = CsvProvider<inferSample, HasHeaders=true>
```

Good data sample, all columns as in `inferSample`. Everything works as expected.
```fsharp
let goodSample = """
"one","two","three"
1,"world",42.42"""

Csv.Parse(goodSample).Rows |> Seq.iter (printfn "%O")
```

Not complete data, column `two` is completely missed:
```fsharp
let missSample = """
"one","three"
1,42.42"""

Csv.Parse(sample2).Rows |> Seq.iter (printfn "%O") // boom!
```

Stack trace:
```
Unhandled Exception: System.Exception: Couldn't parse row 1 according to schema:
 Index was outside the bounds of the array.
   at FSharp.Data.Runtime.CsvHelpers.parseIntoTypedRows@203-6.Invoke(String message) in C:\Git\FSharp.Data\src\Csv\CsvRuntime.fs:line 203
   at FSharp.Data.Runtime.CsvHelpers.parseIntoTypedRows@176.GenerateNext(IEnumerable`1& next) in C:\Git\FSharp.Data\src\Csv\CsvRuntime.fs:line 203
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.oneStepTo@1226[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i)
   at Microsoft.FSharp.Collections.SeqModule.f@4277-2[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i, Unit unitVar0)
   at Microsoft.FSharp.Collections.SeqModule.result@1242.Invoke(Int32 i)
   at Microsoft.FSharp.Collections.IEnumerator.unfold@190.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at Program.main(String[] argv) in c:\temp\CsvProviderExpr\CsvProviderExpr\Program.fs:line 21
```

I tried to add `Schema="two=string option"` with no luck.
Can I somehow handle this case with `CsvProvider`?

**Comment by ovatsus** [comment]
You can use IgnoreErrors=true so that rows with missing columns will be skipped

**Comment by xkrt** [comment]
@ovatsus then all rows will be skipped. I want to parse with single type two possible inputs:
1. with `one`, `two`, `three `columns
2. with `one`, `three` columns (all rows not contains `two` column as well as header row)

**Comment by ovatsus** [comment]
Unfortunately that isn't supported, and won't be easy to. How do you known when there's 2 columns instead of 3, that the missing one is the second one and not the third?

**Comment by xkrt** [comment]
@ovatsus in my case I really know, that `two` maybe missing (and this is ok), not `one` or `three` (if one of them missing - this is error). Yes, my case is special, but it taken from real world (csv data feeds from https://www.whoisxmlapi.com/).

**Comment by ovatsus** [comment]
What solution do you propose?

**Comment by xkrt** [comment]
Honestly, I dont know. I think this issue is rare and can be closed before really good idea appears.
