### ISSUE TITLE
CSV Type Provider causes F# compiler to fail with an "FS0192 impossible" compiler error 

### ISSUE THREAD

**Issue by swlaschin** [fsharp/FSharp.Data#913]
I have a reproducible bug that causes the F# compiler to fail with an "FS0192 impossible" compiler error somewhere in the XmlDocWriter logic.

It only occurs in relation to the CSV Type Provider, so I'm going to assume that the TP is generating bad code somehow. If not, I'll escalate this issue to the main F# compiler project.

The code to reproduce is available here (https://github.com/swlaschin/ImpossibleCompilerError) and can be reproduced in a small module ([MyModule.fs](https://github.com/swlaschin/ImpossibleCompilerError/blob/master/src/ImpossibleCompilerError/MyModule.fs))

Here's a bit of the stack trace:

```
error FS0192 : internal error : impossible [\src\ImpossibleCompilerError\ImpossibleCompilerError.fsproj]

 Unhandled Exception: System.Exception: impossible
            at Microsoft.FSharp.Compiler.Tastops.typeEnc(TcGlobals g, FSharpList`1 gtpsType, FSharpList`1 gtpsMethod, TType ty)
            at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
            at Microsoft.FSharp.Compiler.Tastops.XmlDocArgsEnc(TcGlobals g, FSharpList`1 gtpsType, FSharpList`1 gtpsMethod, FSharpList`1 argTs)
            at Microsoft.FSharp.Compiler.Tastops.XmlDocSigOfVal(TcGlobals g, String path, Val v)
            at Microsoft.FSharp.Compiler.Driver.XmlDocWriter.doValSig@512(TcGlobals tcGlobals, String ptext, Val v)
            at Microsoft.FSharp.Compiler.Driver.XmlDocWriter.doValSig@512-1.Invoke(String ptext, Val v)
            at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
```

**Comment by panesofglass** [comment]
I just tripped this, too. :)

**Comment by swlaschin** [comment]
Good! It's reproducible then!  Ross suggested that it should escalated to the compiler project, as even a buggy TP shouldn't cause an internal error. So I'll do that later...

**Comment by ovatsus** [comment]
Still repros on latest master, though I don't see how we could be doing something wrong in the F#Data code.
Can you create a bug on the FSC or StarterType repos?

**Comment by swlaschin** [comment]
Moved issue to FSC https://github.com/Microsoft/visualfsharp/issues/1143. Thanks!
