### ISSUE TITLE
CsvProvider memory leak

### ISSUE THREAD

**Issue by pavelhritonenko** [fsharp/FSharp.Data#923]
I have to parse long csv-file (~2Gb).
I've written simple script which iterates over the `Rows` and prints every 10000th element.
I expect it would consume constant memory but I have `OutOfMemoryException`.

I'm parsing ip2location database:

    #r "../../packages/FSharp.Data/lib/net40/FSharp.Data.dll"
    
    open System
    open FSharp.Data
    
    type Ips = CsvProvider<"./samples/db14.csv", HasHeaders = false, Schema = "IpFrom(int),IpTo(int),CountryCode,CountryName,Region,City,Latitude,Longtitude,ZipCode(int option),TimeZone,IspName,DomainName,NetSpeed">
    
    let csv = Ips.Load(@"./IP-COUNTRY-REGION-CITY-LATITUDE-LONGITUDE-ZIPCODE-TIMEZONE-ISP-DOMAIN-NETSPEED.csv")
    csv.Rows |> Seq.iteri (fun i x -> if i % 10000 = 1 then printfn "%A" x)

Stacktrace:

    System.Exception: Couldn't parse row 4014978 according to schema: Exception of type 'System.OutOfMemoryException' was thrown.
       at FSharp.Data.Runtime.CsvHelpers.parseIntoTypedRows@203-6.Invoke(String message) in C:\Git\FSharp.Data\src\Csv\CsvRuntime.fs:line 203
       at FSharp.Data.Runtime.CsvHelpers.parseIntoTypedRows@176.GenerateNext(IEnumerable`1& next) in C:\Git\FSharp.Data\src\Csv\CsvRuntime.fs:line 203
       at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
       at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
       at Microsoft.FSharp.Collections.SeqModule.oneStepTo@1403[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i)
       at Microsoft.FSharp.Collections.SeqModule.f@4728-2[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i, Unit unitVar0)
       at Microsoft.FSharp.Collections.SeqModule.result@1419.Invoke(Int32 i)
       at Microsoft.FSharp.Collections.IEnumerator.unfold@236.DoMoveNext(b& )
       at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
       at Microsoft.FSharp.Collections.SeqModule.IterateIndexed[T](FSharpFunc`2 action, IEnumerable`1 source)
       at <StartupCode$FSI_0001>.$FSI_0001.main@() in C:\projects\app-layer\Source\Ip2Location\Script2.fsx:line 8

**Comment by pavelhritonenko** [comment]
Oh... I missed the `CacheRows = true` argument
